plugins {
    id 'java-library'
    alias(libs.plugins.protobuf)
}

dependencyManagement {
    imports {
        mavenBom org.springframework.boot.gradle.plugin.SpringBootPlugin.BOM_COORDINATES
    }
}

dependencies {
    api libs.protobuf.java
    api libs.javatuples
    api libs.zero.allocation.hashing

    compileOnly libs.bundles.lombok
    annotationProcessor libs.bundles.lombok

    compileOnly libs.jspecify
    compileOnly libs.spring.context
    compileOnly libs.slf4j.api

    testImplementation libs.spring.boot.starter.test
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

tasks.named('test') {
    useJUnitPlatform()
}

protobuf {
    protoc {
        artifact = "com.google.protobuf:protoc:${libs.versions.protobuf.get()}"
    }
}
