version: 2
updates:
  # Gradle - Standard Version Catalog
  - package-ecosystem: gradle
    directories:
      - /
    schedule:
      interval: daily
    commit-message:
      prefix: "build"
      prefix-development: "build"
      include: scope
    pull-request-branch-name:
      separator: "/"
    allow:
      - dependency-type: "all"
    versioning-strategy: "auto"

  # Docker
  - package-ecosystem: docker
    directories:
      - /docker
    schedule:
      interval: daily
    commit-message:
      prefix: "build"
      prefix-development: "build"
      include: scope
    pull-request-branch-name:
      separator: "/"

  # Docker Compose
  - package-ecosystem: docker-compose
    directories:
      - /
    schedule:
      interval: daily
    commit-message:
      prefix: "build"
      prefix-development: "build"
      include: scope
    pull-request-branch-name:
      separator: "/"