plugins {
    alias(libs.plugins.quarkus)
    id 'java'
}

dependencies {
    implementation platform(libs.quarkus.bom)
    implementation platform(libs.quarkus.amazon.services.bom)
    implementation project(':shared')

    implementation libs.quarkus.arc
    implementation libs.quarkus.config.yaml
    implementation libs.quarkus.scheduler
    implementation libs.quarkus.vertx.http
    implementation libs.quarkus.kafka.client
    implementation libs.quarkus.hibernate.validator
    implementation libs.quarkus.smallrye.health
    implementation libs.quarkus.micrometer.registry.prometheus
    implementation libs.quarkus.container.image.jib

    implementation libs.quarkus.amazon.s3
    implementation libs.aws.sdk.url.connection.client

    compileOnly libs.bundles.lombok
    annotationProcessor libs.bundles.lombok

    testImplementation libs.quarkus.junit5
}
