plugins {
    alias(libs.plugins.quarkus)
    id 'java'
}

dependencies {
    implementation platform(libs.quarkus.bom)
    implementation project(':shared')

    implementation libs.quarkus.arc
    implementation libs.quarkus.scheduler
    implementation libs.quarkus.vertx.http
    implementation libs.quarkus.messaging.kafka
    implementation libs.quarkus.jdbc.postgresql
    implementation libs.quarkus.flyway
    implementation libs.quarkus.smallrye.health
    implementation libs.quarkus.micrometer.registry.prometheus
    implementation libs.quarkus.container.image.jib

    runtimeOnly libs.flyway.database.postgresql

    compileOnly libs.bundles.lombok
    annotationProcessor libs.bundles.lombok

    testImplementation libs.quarkus.junit5
}
