plugins {
    alias(libs.plugins.spring.boot)
    alias(libs.plugins.spring.dependency.management)
    id 'java'
}

dependencies {
    implementation project(':shared')

    implementation libs.bundles.web
    implementation libs.spring.boot.starter.data.jpa
    implementation libs.datafusion.java

    runtimeOnly libs.postgresql
    runtimeOnly libs.micrometer.registry.prometheus

    compileOnly libs.bundles.lombok
    annotationProcessor libs.bundles.lombok

    testImplementation libs.spring.boot.starter.test
}

bootJar {
    archiveFileName = 'app.jar'
}
