plugins {
    alias(libs.plugins.quarkus)
    id 'java'
}

dependencies {
    implementation platform(libs.quarkus.bom)
    implementation project(':shared')

    implementation libs.quarkus.rest
    implementation libs.quarkus.hibernate.orm
    implementation libs.quarkus.jdbc.postgresql
    implementation libs.quarkus.smallrye.health
    implementation libs.quarkus.micrometer.registry.prometheus
    implementation libs.quarkus.container.image.jib

    compileOnly libs.bundles.lombok
    annotationProcessor libs.bundles.lombok

    testImplementation libs.quarkus.junit5
}
